steps:
  # 1. Build da Imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/zprospector-app:$COMMIT_SHA', '.']

  # 2. Push da Imagem para o Registro
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zprospector-app:$COMMIT_SHA']

  # 3. Deploy Automático no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'zprospector-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/zprospector-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/zprospector-app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY